name: CI

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC
  workflow_dispatch:
    inputs:
      site:
        description: 'Site config name (e.g., example-site)'
        required: false
        type: string

jobs:
  smoke:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    env:
      SITE: ${{ github.event.inputs.site || vars.SMOKE_SITE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start static smoke server (if SITE=static-smoke)
        if: env.SITE == 'static-smoke'
        run: |
          node scripts/static-server.js &
          node scripts/wait-url.js http://127.0.0.1:8080

      - name: Run smoke tests (skips if SITE not set)
        if: env.SITE != ''
        run: node run-tests.js --site=${{ env.SITE }} --profile=smoke

      - name: Skip notice (SITE not set)
        if: env.SITE == ''
        run: |
          echo "Skipping smoke tests. Set repo variable SMOKE_SITE or provide a 'site' input on manual runs."

    concurrency:
      group: smoke-${{ github.ref }}
      cancel-in-progress: true

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.node-version }}
          path: playwright-report
          if-no-files-found: ignore
      - name: Lint
        run: npm run lint
